server:
    port: 8080
spring:
    datasource:
        name: ${POSTGRES_DB}
        url: jdbc:postgresql://${DB_SERVER}/${POSTGRES_DB}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: false
