server:
    port: 8080
spring:
    datasource:
        name: cavalierfou
        url: jdbc:postgresql://localhost:5000/cavalierfou
        username: cavalierfou
        password: db780345
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: false
