server:
    port: 8080
spring:
    datasource:
        name: ${POSTGRES_DB}
        url: jdbc:postgresql://${DB_SERVER}/${POSTGRES_DB}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
        # name: cavalierfou
        # url: jdbc:postgresql://localhost:5000/cavalierfou
        # username: cavalierfou
        # password: db780345
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: false
        