server:
    port: 8080
spring:
    datasource:
        name: ${POSTGRES_DB}
        url: jdbc:postgresql://${DB_SERVER}/${POSTGRES_DB}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
        initialization-mode: always
        schema:
        - classpath:schema.sql
        data:
        - classpath:data.sql
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false
